//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem.UI.Resources.Index {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketSystem.UI.Resources.Index.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveTickets.
        /// </summary>
        public static string ActiveTickets {
            get {
                return ResourceManager.GetString("ActiveTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiDetectedRisk.
        /// </summary>
        public static string AiDetectedRisk {
            get {
                return ResourceManager.GetString("AiDetectedRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiHealth.
        /// </summary>
        public static string AiHealth {
            get {
                return ResourceManager.GetString("AiHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiHelpDesc.
        /// </summary>
        public static string AiHelpDesc {
            get {
                return ResourceManager.GetString("AiHelpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiHelpTitle.
        /// </summary>
        public static string AiHelpTitle {
            get {
                return ResourceManager.GetString("AiHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiInsights.
        /// </summary>
        public static string AiInsights {
            get {
                return ResourceManager.GetString("AiInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiPoweredSupport.
        /// </summary>
        public static string AiPoweredSupport {
            get {
                return ResourceManager.GetString("AiPoweredSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiSuggestions.
        /// </summary>
        public static string AiSuggestions {
            get {
                return ResourceManager.GetString("AiSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriticalTickets.
        /// </summary>
        public static string CriticalTickets {
            get {
                return ResourceManager.GetString("CriticalTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashboardLoadingError.
        /// </summary>
        public static string DashboardLoadingError {
            get {
                return ResourceManager.GetString("DashboardLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleAuthUrlNotConfigured.
        /// </summary>
        public static string GoogleAuthUrlNotConfigured {
            get {
                return ResourceManager.GetString("GoogleAuthUrlNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleLoginPathNotDefined.
        /// </summary>
        public static string GoogleLoginPathNotDefined {
            get {
                return ResourceManager.GetString("GoogleLoginPathNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandingDesc.
        /// </summary>
        public static string LandingDesc {
            get {
                return ResourceManager.GetString("LandingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandingTitle.
        /// </summary>
        public static string LandingTitle {
            get {
                return ResourceManager.GetString("LandingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NeedsAttention.
        /// </summary>
        public static string NeedsAttention {
            get {
                return ResourceManager.GetString("NeedsAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewTicket.
        /// </summary>
        public static string NewTicket {
            get {
                return ResourceManager.GetString("NewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable.
        /// </summary>
        public static string Stable {
            get {
                return ResourceManager.GetString("Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartWithGoogle.
        /// </summary>
        public static string StartWithGoogle {
            get {
                return ResourceManager.GetString("StartWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketsToday.
        /// </summary>
        public static string TicketsToday {
            get {
                return ResourceManager.GetString("TicketsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopProblems.
        /// </summary>
        public static string TopProblems {
            get {
                return ResourceManager.GetString("TopProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAi.
        /// </summary>
        public static string OpenAi {
            get {
                return ResourceManager.GetString("OpenAi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ViewAll.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ViewAllTickets.
        /// </summary>
        public static string ViewAllTickets {
            get {
                return ResourceManager.GetString("ViewAllTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WelcomeBack.
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
    }
}
