//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem.UI.Resources.Ticket {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TicketResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicketResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketSystem.UI.Resources.Ticket.TicketResource", typeof(TicketResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiCommunicationError.
        /// </summary>
        public static string AiCommunicationError {
            get {
                return ResourceManager.GetString("AiCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiFieldsAutoFilled.
        /// </summary>
        public static string AiFieldsAutoFilled {
            get {
                return ResourceManager.GetString("AiFieldsAutoFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiHelp.
        /// </summary>
        public static string AiHelp {
            get {
                return ResourceManager.GetString("AiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string Assignee {
            get {
                return ResourceManager.GetString("Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignTo.
        /// </summary>
        public static string AssignTo {
            get {
                return ResourceManager.GetString("AssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionPlaceholder.
        /// </summary>
        public static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorLoadingForm.
        /// </summary>
        public static string ErrorLoadingForm {
            get {
                return ResourceManager.GetString("ErrorLoadingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorLoadingTicketData.
        /// </summary>
        public static string ErrorLoadingTicketData {
            get {
                return ResourceManager.GetString("ErrorLoadingTicketData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorSubmittingRequest.
        /// </summary>
        public static string ErrorSubmittingRequest {
            get {
                return ResourceManager.GetString("ErrorSubmittingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializationError.
        /// </summary>
        public static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyTickets.
        /// </summary>
        public static string MyTickets {
            get {
                return ResourceManager.GetString("MyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewTicket.
        /// </summary>
        public static string NewTicket {
            get {
                return ResourceManager.GetString("NewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments yet..
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tickets found.
        /// </summary>
        public static string NoTickets {
            get {
                return ResourceManager.GetString("NoTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoTicketsDesc.
        /// </summary>
        public static string NoTicketsDesc {
            get {
                return ResourceManager.GetString("NoTicketsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProblemPlaceholder.
        /// </summary>
        public static string ProblemPlaceholder {
            get {
                return ResourceManager.GetString("ProblemPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProblemTitle.
        /// </summary>
        public static string ProblemTitle {
            get {
                return ResourceManager.GetString("ProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestDescription.
        /// </summary>
        public static string RequestDescription {
            get {
                return ResourceManager.GetString("RequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestSubmissionError.
        /// </summary>
        public static string RequestSubmissionError {
            get {
                return ResourceManager.GetString("RequestSubmissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetAllFilters.
        /// </summary>
        public static string ResetAllFilters {
            get {
                return ResourceManager.GetString("ResetAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchError.
        /// </summary>
        public static string SearchError {
            get {
                return ResourceManager.GetString("SearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchTickets.
        /// </summary>
        public static string SearchTickets {
            get {
                return ResourceManager.GetString("SearchTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemanticTicketSearch.
        /// </summary>
        public static string SemanticTicketSearch {
            get {
                return ResourceManager.GetString("SemanticTicketSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerError.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerProblemTryAgain.
        /// </summary>
        public static string ServerProblemTryAgain {
            get {
                return ResourceManager.GetString("ServerProblemTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitTicket.
        /// </summary>
        public static string SubmitTicket {
            get {
                return ResourceManager.GetString("SubmitTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketCreatedSuccessfully.
        /// </summary>
        public static string TicketCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TicketCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketsDescription.
        /// </summary>
        public static string TicketsDescription {
            get {
                return ResourceManager.GetString("TicketsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketSearchError.
        /// </summary>
        public static string TicketSearchError {
            get {
                return ResourceManager.GetString("TicketSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketUpdatedSuccessfully.
        /// </summary>
        public static string TicketUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TicketUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadHint.
        /// </summary>
        public static string UploadHint {
            get {
                return ResourceManager.GetString("UploadHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment....
        /// </summary>
        public static string WriteComment {
            get {
                return ResourceManager.GetString("WriteComment", resourceCulture);
            }
        }
    }
}
