//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem.UI.Resources.DocumentAi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentAiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentAiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketSystem.UI.Resources.DocumentAi.DocumentAiResource", typeof(DocumentAiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Document Assistant answer:.
        /// </summary>
        public static string AiAnswerCommentPrefix {
            get {
                return ResourceManager.GetString("AiAnswerCommentPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your Llama&apos;s answer:.
        /// </summary>
        public static string AiAnswerTitle {
            get {
                return ResourceManager.GetString("AiAnswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze and Answer.
        /// </summary>
        public static string AnalyzeButton {
            get {
                return ResourceManager.GetString("AnalyzeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Attach the answer to a ticket.
        /// </summary>
        public static string AttachToTicketLabel {
            get {
                return ResourceManager.GetString("AttachToTicketLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audio recording of the answer:.
        /// </summary>
        public static string AudioAnswerLabel {
            get {
                return ResourceManager.GetString("AudioAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support the audio element..
        /// </summary>
        public static string AudioNotSupported {
            get {
                return ResourceManager.GetString("AudioNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected client-side error:.
        /// </summary>
        public static string ClientErrorPrefix {
            get {
                return ResourceManager.GetString("ClientErrorPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to add the comment to the ticket..
        /// </summary>
        public static string CommentAddedError {
            get {
                return ResourceManager.GetString("CommentAddedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The answer was added to the ticket as a comment..
        /// </summary>
        public static string CommentAddedSuccess {
            get {
                return ResourceManager.GetString("CommentAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommsCenter AI - Document Search.
        /// </summary>
        public static string DocumentAiTitle {
            get {
                return ResourceManager.GetString("DocumentAiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system returned an empty text response..
        /// </summary>
        public static string EmptyResponse {
            get {
                return ResourceManager.GetString("EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string LanguageSerbian {
            get {
                return ResourceManager.GetString("LanguageSerbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backend is analyzing the document, computing embeddings and generating an answer... (this can take a while).
        /// </summary>
        public static string LoadingStageAnalyze {
            get {
                return ResourceManager.GetString("LoadingStageAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading and preparing the file from your computer....
        /// </summary>
        public static string LoadingStageUpload {
            get {
                return ResourceManager.GetString("LoadingStageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.g. What are the key deadlines on the project?.
        /// </summary>
        public static string QuestionPlaceholder {
            get {
                return ResourceManager.GetString("QuestionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file:.
        /// </summary>
        public static string SelectedFilePrefix {
            get {
                return ResourceManager.GetString("SelectedFilePrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a ticket....
        /// </summary>
        public static string SelectTicketPlaceholder {
            get {
                return ResourceManager.GetString("SelectTicketPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send to ticket.
        /// </summary>
        public static string SendToTicketButton {
            get {
                return ResourceManager.GetString("SendToTicketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Choose a document (PDF or TXT).
        /// </summary>
        public static string Step1Label {
            get {
                return ResourceManager.GetString("Step1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AI will read the generated answer aloud in the selected language..
        /// </summary>
        public static string Step2Hint {
            get {
                return ResourceManager.GetString("Step2Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Choose the language for the audio answer.
        /// </summary>
        public static string Step2Label {
            get {
                return ResourceManager.GetString("Step2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Ask a question about the document.
        /// </summary>
        public static string Step3Label {
            get {
                return ResourceManager.GetString("Step3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed, but the server did not return error details..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
