<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <WasmFingerprintAssets>false</WasmFingerprintAssets>
	  <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.LocalStorage.WebAssembly" Version="9.0.1" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="LocalStorage" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="11.0.0-preview.2.26159.112" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="11.0.0-preview.3.26207.106" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="State\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Index\IndexResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IndexResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Ticket\TicketResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TicketResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\User\UserResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UserResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DocumentAi\DocumentAiResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DocumentAiResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Index\IndexResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>IndexResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Ticket\TicketResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>TicketResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\User\UserResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UserResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DocumentAi\DocumentAiResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DocumentAiResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
